version: "3.8"
services:
  db:
    container_name: "postgres"
    image: postgres:16.3-bookworm
    shm_size: 2g
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/slack-ip-bot/postgres_data:/var/lib/postgresql/data  # ✅ DB 데이터 영속화
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 6s

  slack_ip_bot:
    container_name: "slack_ip_bot"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/slack-ip-bot/log:/app/log
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000