# Generated by Django 5.2.4 on 2025-07-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('requester', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'IP Access Request',
                'verbose_name_plural': 'IP Access Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
