# Generated by Django 5.2.4 on 2025-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaccessrequest',
            name='from_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaccessrequest',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipaccessrequest',
            name='to_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
