# Generated by Django 5.2.4 on 2025-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0002_ipaccessrequest_from_port_ipaccessrequest_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('group_id', models.CharField(max_length=100)),
                ('from_port', models.IntegerField()),
                ('to_port', models.IntegerField()),
                ('requester', models.CharField(max_length=100)),
                ('old_expires_at', models.DateTimeField(blank=True, null=True)),
                ('new_expires_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Access Log',
                'verbose_name_plural': 'IP Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='ipaccessrequest',
            name='list_type',
        ),
    ]
