# Generated by Django 5.2.4 on 2025-07-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0003_ipaccesslog_remove_ipaccessrequest_list_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaccessrequest',
            name='type',
        ),
    ]
