# Generated by Django 5.2.4 on 2025-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0004_remove_ipaccessrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaccesslog',
            name='protocol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ipaccessrequest',
            name='protocol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
